// Generated by gencpp from file actionlib_demo/ReadBookResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_DEMO_MESSAGE_READBOOKRESULT_H
#define ACTIONLIB_DEMO_MESSAGE_READBOOKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_demo
{
template <class ContainerAllocator>
struct ReadBookResult_
{
  typedef ReadBookResult_<ContainerAllocator> Type;

  ReadBookResult_()
    : is_finish(false)  {
    }
  ReadBookResult_(const ContainerAllocator& _alloc)
    : is_finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_finish_type;
  _is_finish_type is_finish;





  typedef boost::shared_ptr< ::actionlib_demo::ReadBookResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_demo::ReadBookResult_<ContainerAllocator> const> ConstPtr;

}; // struct ReadBookResult_

typedef ::actionlib_demo::ReadBookResult_<std::allocator<void> > ReadBookResult;

typedef boost::shared_ptr< ::actionlib_demo::ReadBookResult > ReadBookResultPtr;
typedef boost::shared_ptr< ::actionlib_demo::ReadBookResult const> ReadBookResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_demo::ReadBookResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_demo': ['/home/linux/catkin_ws/devel/share/actionlib_demo/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_demo::ReadBookResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_demo::ReadBookResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_demo::ReadBookResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b856346ef49f692419615fadca72182";
  }

  static const char* value(const ::actionlib_demo::ReadBookResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b856346ef49f692ULL;
  static const uint64_t static_value2 = 0x419615fadca72182ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_demo/ReadBookResult";
  }

  static const char* value(const ::actionlib_demo::ReadBookResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
bool is_finish\n\
";
  }

  static const char* value(const ::actionlib_demo::ReadBookResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadBookResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_demo::ReadBookResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_demo::ReadBookResult_<ContainerAllocator>& v)
  {
    s << indent << "is_finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_DEMO_MESSAGE_READBOOKRESULT_H
